# Generated by Django 6.1 on 2026-08-17 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('completed_experiences', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.choice')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.experience')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.userprogress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
