# Generated by Django 6.1 on 2026-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_userprogress_answerattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
