# Generated by Django 6.1 on 2026-09-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_userprogress_wallet_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="journey",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Course number in the curriculum. Course N+1 stays locked until course N is passed with a 100% score.",
            ),
        ),
        migrations.CreateModel(
            name="JourneyAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.PositiveIntegerField()),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.journey",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_attempts",
                        to="learning.userprogress",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="answerattempt",
            name="journey_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="learning.journeyattempt",
            ),
        ),
    ]
