# Generated by Django 6.1 on 2026-09-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0003_userprogress_wallet_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Mint LEARN token"), (1, "Mint achievement NFT")]
                    ),
                ),
                ("wallet_address", models.CharField(max_length=42)),
                ("token_address", models.CharField(max_length=42)),
                ("amount", models.CharField(default="0", max_length=78)),
                ("uri", models.CharField(blank=True, max_length=300)),
                ("nonce", models.CharField(max_length=66, unique=True)),
                ("expiry", models.PositiveBigIntegerField()),
                ("signature", models.CharField(max_length=132)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_vouchers",
                        to="learning.experience",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_vouchers",
                        to="learning.journey",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_vouchers",
                        to="learning.userprogress",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("experience__isnull", False)),
                        fields=("progress", "experience"),
                        name="unique_voucher_per_progress_experience",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("journey__isnull", False)),
                        fields=("progress", "journey"),
                        name="unique_voucher_per_progress_journey",
                    ),
                ],
            },
        ),
    ]
