# Generated by Django 6.1 on 2026-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0004_alter_journey_options_journey_order_journeyattempt_and_more",
        ),
        ("reward", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rewardvoucher",
            name="unique_voucher_per_progress_journey",
        ),
        migrations.AddField(
            model_name="rewardvoucher",
            name="is_greencard",
            field=models.BooleanField(
                default=False,
                help_text="The single Chiliz Greencard NFT unlocked by passing every core course, as opposed to a per-journey badge.",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardvoucher",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_greencard", True)),
                fields=("progress",),
                name="unique_greencard_voucher_per_progress",
            ),
        ),
        migrations.RemoveField(
            model_name="rewardvoucher",
            name="journey",
        ),
    ]
